### ISSUE TITLE
Horizontal scalability experiment reproduction

### ISSUE THREAD

**Issue by ljm0022** [mSvcBench/muBench#8]
Hi, thank you and your team for open-sourcing the benchmark code for microservice applications. I want to reproduce the experimental results in your paper. However, in the file, I couldn't find the code to test the scaling performance. Can you explain the flow of the horizontal scaling experiment?

**Comment by ludovicofunari** [comment]
Thank you for your interest in our work. 

> Can you explain the flow of the horizontal scaling experiment?

Yes, basically, we have considered two types of scaling experiments using as reference the CPU utilisation set at 70% (_DesMV_), named _flat_ and _tuned_. As reference, you can dive deeper into section **4.3 Horizontal scalability** of the paper and the related **Figure 9**.
In the _flat_ case, we have considered a fixed CPU request per Pod, namely 100m, 300m, and 600m. Instead, in the _tuned_ case, we have considered the following strategy to evaluate the CPU request per Pod:
1. We have deployed the application using one replica per microservice.
2. We then generated a volume of user requests to the application to reach the CPU utilisation threshold set at 50% per node.
3. We then took a snapshot of the CPU utilisation of each microservice, calculated the average CPU utilisation of each microservice U<sub>cpu</sub>(i) and set the CPU request per Pod as: R<sub>cpu</sub>(i) = U<sub>cpu</sub>(i) / DesMV.

It turns out from the experiments that almost all the microservices are practically unloaded, for this, we have set a minimum value of 50m each, while `s0`, `s4`, `s8`, and `s29` required 1118m, 1385m, 1260m, 745m respectively.

As for the autoscaling, we have set the cpu-percent to 70% and the maximum number of replicas to 10:
```bash
   kubectl autoscale deployment s${i} --cpu-percent=70 --min=1 --max=10
```
Where _s${i}_, in this case, is the name of all the services of the application using Topology A (see Figure 4a in the paper).

**Comment by ljm0022** [comment]
Thanks for your answer. In the tuned case, did you dynamically adjust the value of cpu-requests in the workmodel.json file?

**Comment by andreadetti** [comment]
yes, exactly.

**Comment by ljm0022** [comment]
Thanks your explanation, I understand.
